### ISSUE TITLE
Please update to delve 1.20.1 to support Golang 1.20

### ISSUE THREAD

**Issue by manno** [rancherlabs/delve-debugger#1]
See https://github.com/go-delve/delve/blob/master/CHANGELOG.md#1201-2022-12-12

Without this debugging fleet fails with:

```
If you don't see a command prompt, try pressing enter.
panic: <nil> not an Int

goroutine 1 [running]:
go/constant.Int64Val({0x0?, 0x0?})
	/usr/lib64/go/1.18/src/go/constant/value.go:504 +0x12c
github.com/go-delve/delve/pkg/proc.(*Variable).parseG.func2({0x5e12fd?, 0x40062f1808?})
	/root/go/pkg/mod/github.com/go-delve/delve@v1.9.1/pkg/proc/variables.go:885 +0x50
github.com/go-delve/delve/pkg/proc.(*Variable).parseG(0x6a9b40?)
	/root/go/pkg/mod/github.com/go-delve/delve@v1.9.1/pkg/proc/variables.go:921 +0x788
github.com/go-delve/delve/pkg/proc.GetG({0x6a9b40, 0x4000200000})
	/root/go/pkg/mod/github.com/go-delve/delve@v1.9.1/pkg/proc/variables.go:259 +0xcc
github.com/go-delve/delve/pkg/proc.NewTarget({0x6aa210, 0x400011c800}, 0x1, {0x6a9b40?, 0x4000200000}, {{0x40000b5540, 0xb}, {0x0, 0x0, 0x0}, ...})
	/root/go/pkg/mod/github.com/go-delve/delve@v1.9.1/pkg/proc/target.go:211 +0x2d8
github.com/go-delve/delve/pkg/proc/native.(*nativeProcess).initialize(0x400011c800, {0x40000b5540, 0xb}, {0x0, 0x0, 0x0})
	/root/go/pkg/mod/github.com/go-delve/delve@v1.9.1/pkg/proc/native/proc.go:242 +0xf4
github.com/go-delve/delve/pkg/proc/native.Attach(0x4000183260?, {0x0, 0x0, 0x0})
	/root/go/pkg/mod/github.com/go-delve/delve@v1.9.1/pkg/proc/native/proc_linux.go:157 +0x16c
github.com/go-delve/delve/service/debugger.(*Debugger).Attach(0x4000183260?, 0x4000000004?, {0x0?, 0x5?})
	/root/go/pkg/mod/github.com/go-delve/delve@v1.9.1/service/debugger/debugger.go:347 +0x114
github.com/go-delve/delve/service/debugger.New(0x40001442a0, {0x40001085b0, 0x0, 0x8})
	/root/go/pkg/mod/github.com/go-delve/delve@v1.9.1/service/debugger/debugger.go:158 +0x558
github.com/go-delve/delve/service/rpccommon.(*ServerImpl).Run(0x4000084f00)
	/root/go/pkg/mod/github.com/go-delve/delve@v1.9.1/service/rpccommon/server.go:122 +0xd4
github.com/go-delve/delve/cmd/dlv/cmds.execute(0x1, {0x40001085b0, 0x0, 0x8}, 0x40001441c0, {0x0, 0x0}, 0x3, {0x40001085a0, 0x1, ...}, ...)
	/root/go/pkg/mod/github.com/go-delve/delve@v1.9.1/cmd/dlv/cmds/commands.go:987 +0xb64
github.com/go-delve/delve/cmd/dlv/cmds.attachCmd(0x4000168780?, {0x40001085a0?, 0x1, 0x9})
	/root/go/pkg/mod/github.com/go-delve/delve@v1.9.1/cmd/dlv/cmds/commands.go:787 +0x104
github.com/spf13/cobra.(*Command).execute(0x4000168780, {0x4000108510, 0x9, 0x9})
	/root/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:856 +0x4c4
github.com/spf13/cobra.(*Command).ExecuteC(0x4000168500)
	/root/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960 +0x358
github.com/spf13/cobra.(*Command).Execute(...)
	/root/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:897
main.main()
	/root/go/pkg/mod/github.com/go-delve/delve@v1.9.1/cmd/dlv/main.go:24 +0x188
Session ended, the ephemeral container will not be restarted but may be reattached using 'kubectl attach fleet-controller-5c65dfd55f-94m94 -c debugger-gck6c -i -t' if it is still running
```

**Comment by moio** [comment]
Latest version should have this fixed, please feel free to reopen or open a new issue in case you encounter any further difficulties.

Thanks for reporting!
